In [2]:
import pandas as pd

In [44]:
fragile_index = pd.read_csv('../GlobalEconomy dataset/data/fragile_state_index.csv')

In [45]:
innovation = pd.read_csv('../GlobalEconomy dataset/data/innovation_measures.csv')

In [46]:
globalisation = pd.read_csv('../GlobalEconomy dataset/data/globalisation.csv')

In [47]:
infrastructures = pd.read_csv('../GlobalEconomy dataset/data/infrastructure_and_transport_characteristics.csv')

In [48]:
fragile_index.columns

Index(['Country', 'Code', 'ContinentCode', 'Year',
       'Fragile state index 0 (low) - 120 (high)',
       'Security threats index 0 (low) - 10 (high)',
       'Factionalized elites index 0 (low) - 10 (high)',
       'Group grievance index 0 (low) - 10 (high)',
       'Economic decline index 0 (low) - 10 (high)',
       'Uneven economic development index 0 (low) - 10 (high)',
       'Human flight and brain drain index 0 (low) - 10 (high)',
       'State legitimacy index 0 (high) - 10 (low)',
       'Public services index 0 (high) - 10 (low)',
       'Human rights and rule of law index 0 (high) - 10 (low)',
       'Demographic pressures 0 (low) - 10 (high)',
       'Refugees and displaced persons index 0 (low) - 10 (high)',
       'External interventions index 0 (low) - 10 (high)'],
      dtype='object')

In [49]:
fragile_index.columns = ['country', 'code', 'continentcode', 'year',
       'fragile_state_index',
       'security_threats_index',
       'factionalized_elites_index',
       'group_grievance_index',
       'economic_decline_index',
       'uneven_economic_development',
       'human_flight_and_brain_drain',
       'state_legitimacy_index',
       'public_services_index',
       'human_rights_and_rule_of_law_index',
       'demographic_pressures',
       'refugees_and_displaced_persons_index',
       'external_interventions_index']


# fragile_state_index 0 (low) - 120 (high)',
# other indexes from 0 to 10

In [50]:
fragile_index['year'].unique()

array([2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
       2018, 2019, 2020, 2021, 2022, 2023])

In [51]:
fragile_index

,country,code,continentcode,year,fragile_state_index,security_threats_index,factionalized_elites_index,group_grievance_index,economic_decline_index,uneven_economic_development,human_flight_and_brain_drain,state_legitimacy_index,public_services_index,human_rights_and_rule_of_law_index,demographic_pressures,refugees_and_displaced_persons_index,external_interventions_index
0,Afghanistan,AFG,AS,2007,102.3,9.0,8.5,9.1,8.3,8.0,7.0,8.8,8.0,8.2,8.5,8.9,10.0
1,Afghanistan,AFG,AS,2008,105.4,9.6,8.8,9.5,8.5,8.1,7.0,9.2,8.3,8.4,9.1,8.9,10.0
2,Afghanistan,AFG,AS,2009,108.2,9.9,9.1,9.6,8.3,8.4,7.2,9.8,8.9,8.8,9.3,8.9,10.0
3,Afghanistan,AFG,AS,2010,109.3,9.7,9.4,9.7,8.3,8.2,7.2,10.0,8.9,9.2,9.5,9.2,10.0
4,Afghanistan,AFG,AS,2011,107.5,9.8,9.4,9.3,8.0,8.4,7.2,9.7,8.5,8.8,9.1,9.3,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2986,Zimbabwe,ZWE,AF,2019,99.5,8.8,10.0,6.7,8.1,7.9,7.3,9.4,8.6,8.2,9.0,8.2,7.3
2987,Zimbabwe,ZWE,AF,2020,99.2,8.5,10.0,6.4,8.6,7.6,7.0,9.1,8.7,8.3,9.3,8.5,7.2
2988,Zimbabwe,ZWE,AF,2021,99.1,8.6,10.0,6.1,9.4,7.7,7.1,8.8,9.0,8.0,9.3,8.2,6.9
2989,Zimbabwe,ZWE,AF,2022,97.8,8.7,9.9,5.8,9.1,7.7,7.0,8.9,8.7,8.1,9.0,7.9,7.0
2990,Zimbabwe,ZWE,AF,2023,96.9,8.4,10.0,5.9,9.2,7.8,7.1,8.9,8.8,NaN,8.7,7.6,NaN

In [52]:
fragile_index.isnull().sum()

country                                   0
code                                      0
continentcode                           322
year                                      0
fragile_state_index                       0
security_threats_index                    0
factionalized_elites_index                0
group_grievance_index                     0
economic_decline_index                    0
uneven_economic_development               0
human_flight_and_brain_drain              0
state_legitimacy_index                    1
public_services_index                     0
human_rights_and_rule_of_law_index      177
demographic_pressures                     0
refugees_and_displaced_persons_index      0
external_interventions_index            177
dtype: int64

In [53]:
fragile_index = fragile_index.drop(columns=['continentcode'])

In [54]:
fragile_index.to_csv('./global_economy/fragile_index.csv')

In [17]:
innovation.columns

Index(['Country', 'Code', 'ContinentCode', 'Year', 'Innovations index (0-100)',
       'Research and development expenditure percent of GDP',
       'Information technology exports percent of total goods exports',
       'High technology exports',
       'High tech exports percent of manufactured exports',
       'Patent applications by residents'],
      dtype='object')

In [18]:
innovation.columns = ['country', 'code', 'continentcode', 'year', 'innovations_index',
       'research_and_development_expenditure_percent_of_gdp',
       'information_technology_exports_percent_of total_goods_exports',
       'high_technology_exports',
       'high_tech_exports_percent_of_manufactured_exports',
       'patent_applications_by_residents']

In [21]:
innovation = innovation.loc[innovation['year']>=2004]
innovation

,country,code,continentcode,year,innovations_index,research_and_development_expenditure_percent_of_gdp,information_technology_exports_percent_of total_goods_exports,high_technology_exports,high_tech_exports_percent_of_manufactured_exports,patent_applications_by_residents
0,Afghanistan,AFG,AS,2018,NaN,NaN,0.00,0.00,0.00,NaN
1,Afghanistan,AFG,AS,2019,NaN,NaN,0.01,0.00,0.00,NaN
6,Albania,ALB,EU,2004,NaN,NaN,0.47,NaN,NaN,NaN
7,Albania,ALB,EU,2005,NaN,NaN,0.59,NaN,NaN,NaN
8,Albania,ALB,EU,2006,NaN,NaN,0.88,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
5365,Zimbabwe,ZWE,AF,2018,23.1,NaN,0.02,9.71,2.06,NaN
5366,Zimbabwe,ZWE,AF,2019,22.3,NaN,0.03,27.78,4.95,NaN
5367,Zimbabwe,ZWE,AF,2020,20.0,NaN,0.05,8.28,2.38,NaN
5368,Zimbabwe,ZWE,AF,2021,21.9,NaN,0.01,5.02,1.08,NaN
5369,Zimbabwe,ZWE,AF,2022,18.1,NaN,NaN,7.82,1.48,NaN

In [39]:
innovation.to_csv('./global_economy/innovation.csv')

In [29]:
innovation.isnull().sum()

country                                                             0
code                                                                0
continentcode                                                     402
year                                                                0
innovations_index                                                1593
research_and_development_expenditure_percent_of_gdp              1572
information_technology_exports_percent_of total_goods_exports     418
high_technology_exports                                           887
high_tech_exports_percent_of_manufactured_exports                 910
patent_applications_by_residents                                 1252
dtype: int64

In [23]:
globalisation.columns

Index(['Country', 'Code', 'ContinentCode', 'Year',
       'Globalization index (0-100)', 'Economic globalization index (0-100)',
       'Political globalization index (0-100)',
       'Social globalization index (0-100)'],
      dtype='object')

In [24]:
globalisation.columns = ['country', 'code', 'continentcode', 'year',
       'globalization_index', 'economic_globalization_index',
       'political_globalization_index',
       'social_globalization_index']

In [26]:
globalisation = globalisation.loc[globalisation['year']>=2004]

In [28]:
globalisation.isnull().sum()

country                            0
code                               0
continentcode                    441
year                               0
globalization_index               35
economic_globalization_index     165
political_globalization_index      0
social_globalization_index         0
dtype: int64

In [40]:
globalisation.to_csv('./global_economy/globalisation.csv')

In [12]:
infrastructures.columns

Index(['Country', 'Code', 'ContinentCode', 'Year',
       'Internet users percent of population',
       'Broadband internet subscribers in thousands',
       'Fixed broadband internet subscribers per 100 people',
       'Mobile phone subscribers in millions',
       'Mobile phone subscribers per 100 people',
       'Mobile network coverage percent of the population',
       'International Internet bandwidth per Internet user kb/s',
       'Airline passengers of domestically owned airlines',
       'Railroad lines total length in km',
       'Volume of goods transported by railways', 'Railway passengers',
       'Number of 20-foot containers passing through the ports',
       'New passenger car sales numbers per year',
       'New commercial vehicle sales numbers per year',
       'Quality of roads 1(low) - 7(high)',
       'Quality of railroad infrastructure 1(low) - 7(high)',
       'Quality of port infrastructure 1(low) - 7(high)',
       'Quality of air transport infrastructure 1(low) - 7(high)'],
      dtype='object')

In [13]:
infrastructures.columns = ['country', 'code', 'continentcode', 'year',
       'internet_users_percent_of_population',
       'broadband_internet_subscribers_in_thousands',
       'fixed_broadband_internet_subscribers_per_100_people',
       'mobile_phone_subscribers_in_millions',
       'mobile_phone_subscribers_per_100_people',
       'mobile_network_coverage_percent_of_the_population',
       'international_internet_bandwidth_per_internet_user_kb/s',
       'airline_passengers_of_domestically_owned_airlines',
       'railroad_lines_total_length_in_km',
       'volume_of_goods_transported_by_railways', 'railway_passengers',
       'number_of_20foot_containers_passing_through_the_ports',
       'new_passenger_car_sales_numbers_per_year',
       'new_commercial_vehicle_sales_numbers_per_year',
       'quality_roads',
       'quality_railroad infrastructure',
       'quality_port_infrastructure',
       'quality_air_transport_infrastructure']

In [14]:
infrastructures = infrastructures.loc[infrastructures['year']>=2004]

In [15]:
infrastructures.to_csv('./global_economy/infrastructures.csv')

In [16]:
infrastructures.isnull().sum()

country                                                       0
code                                                          0
continentcode                                               463
year                                                          0
internet_users_percent_of_population                        277
broadband_internet_subscribers_in_thousands                 466
fixed_broadband_internet_subscribers_per_100_people         310
mobile_phone_subscribers_in_millions                         66
mobile_phone_subscribers_per_100_people                      73
mobile_network_coverage_percent_of_the_population          3026
international_internet_bandwidth_per_internet_user_kb/s    3010
airline_passengers_of_domestically_owned_airlines          1036
railroad_lines_total_length_in_km                          2420
volume_of_goods_transported_by_railways                    2409
railway_passengers                                         2415
number_of_20foot_containers_passing_through_the_ports      1479
new_passenger_car_sales_numbers_per_year                   1451
new_commercial_vehicle_sales_numbers_per_year              1562
quality_roads                                              1804
quality_railroad infrastructure                            2463
quality_port_infrastructure                                1810
quality_air_transport_infrastructure                       1806
dtype: int64

In [17]:
infrastructures.columns

Index(['country', 'code', 'continentcode', 'year',
       'internet_users_percent_of_population',
       'broadband_internet_subscribers_in_thousands',
       'fixed_broadband_internet_subscribers_per_100_people',
       'mobile_phone_subscribers_in_millions',
       'mobile_phone_subscribers_per_100_people',
       'mobile_network_coverage_percent_of_the_population',
       'international_internet_bandwidth_per_internet_user_kb/s',
       'airline_passengers_of_domestically_owned_airlines',
       'railroad_lines_total_length_in_km',
       'volume_of_goods_transported_by_railways', 'railway_passengers',
       'number_of_20foot_containers_passing_through_the_ports',
       'new_passenger_car_sales_numbers_per_year',
       'new_commercial_vehicle_sales_numbers_per_year', 'quality_roads',
       'quality_railroad infrastructure', 'quality_port_infrastructure',
       'quality_air_transport_infrastructure'],
      dtype='object')

In [19]:
quality_infrastructures = infrastructures.drop(columns = ['internet_users_percent_of_population',
       'broadband_internet_subscribers_in_thousands',
       'fixed_broadband_internet_subscribers_per_100_people',
       'mobile_phone_subscribers_in_millions',
       'mobile_phone_subscribers_per_100_people',
       'mobile_network_coverage_percent_of_the_population',
       'international_internet_bandwidth_per_internet_user_kb/s',
       'airline_passengers_of_domestically_owned_airlines',
       'railroad_lines_total_length_in_km',
       'volume_of_goods_transported_by_railways', 'railway_passengers',
       'number_of_20foot_containers_passing_through_the_ports',
       'new_passenger_car_sales_numbers_per_year',
       'new_commercial_vehicle_sales_numbers_per_year'])

In [21]:
quality_infrastructures.to_csv('./global_economy/quality_infrastructures.csv')

In [32]:
sri = pd.read_csv('./fundforpeace/state_resilient_index.csv', sep=';')

In [36]:
sri.columns = ['country', 'inclusion', 'social_cohesion', 'state_capacity',
       'individual_capabilities_resources', 'environment_ecology',
       'economy', 'civic_space', 'capacity_score']

In [39]:
sri['country'].unique()

array(['New Zealand', 'Norway', 'Sweden', 'Finland', 'Canada', 'Paraguay',
       'Australia', 'Central African Republic', 'Slovenia', 'Austria',
       'Brazil', 'Switzerland', 'Costa Rica', 'Colombia', 'Latvia',
       'Zambia', 'Gabon', 'Romania', 'Lithuania', 'United Kingdom',
       'Ecuador', 'Croatia', 'Chile', 'France', 'Estonia', 'Bolivia',
       'Panama', 'Ireland', 'Denmark', 'Malawi', 'Spain', 'Peru',
       'Germany', 'Slovakia', 'Congo Democratic Republic', 'Albania',
       'Japan', 'Venezuela', 'Uruguay', 'Portugal', 'Uganda', 'Laos',
       'Namibia', 'United States', 'Nepal', 'Congo Republic', 'Greece',
       'Netherlands', 'Russia', 'Italy', 'Mozambique', 'Czechia',
       'Hungary', 'Nicaragua', 'Equatorial Guinea', 'Poland',
       'Tajikistan', 'Bulgaria', 'Belgium', 'Mongolia', 'Honduras',
       'Georgia', 'Ethiopia', 'Cameroon', 'Mali', 'Kyrgyzstan',
       'Malaysia', 'Niger', 'Papua New Guinea', 'Mexico', 'Argentina',
       'Kazakhstan', 'Guinea', 'Botswana', 'Burundi', 'Cambodia',
       'Belarus', 'Zimbabwe', 'North Macedonia', 'Serbia', 'Timor-Leste',
       'Sierra Leone', 'United Arab Emirates', 'Myanmar', 'Burkina Faso',
       'South Korea', 'Dominican Republic', 'Rwanda', 'Thailand', 'Chad',
       'Angola', 'Kenya', 'Ghana', 'Indonesia', 'Tanzania', 'Armenia',
       'Ukraine', 'Guinea Bissau', 'Senegal', 'Jamaica', 'Benin',
       'Bosnia and Herzegovina', 'Morocco', 'Cuba', 'Trinidad and Tobago',
       'Sri Lanka', 'Lesotho', 'Philippines', 'Togo', 'El Salvador',
       'Kuwait', 'Guatemala', 'Nigeria', 'Vietnam', "Cote d'Ivoire",
       'South Africa', 'Sudan', 'Turkey', 'Azerbaijan', 'Liberia',
       'Madagascar', 'South Sudan', 'Cyprus', 'Singapore', 'Jordan',
       'Israel', 'Moldova', 'Egypt', 'Iraq', 'Bahrain', 'Bangladesh',
       'Gambia', 'Saudi Arabia', 'Somalia', 'Mauritania', 'China', 'Oman',
       'Pakistan', 'Eswatini', 'India', 'Palestine', 'Iran', 'Qatar',
       'Tunisia', 'Turkmenistan', 'Afghanistan', 'Algeria', 'Haiti',
       'Uzbekistan', 'Mauritius', 'Lebanon', 'Yemen', 'Libya', 'Syria'],
      dtype=object)

In [40]:
country_code_map = {
    'New Zealand': 'NZ',
    'Norway': 'NO',
    'Sweden': 'SE',
    'Finland': 'FI',
    'Canada': 'CA',
    'Paraguay': 'PY',
    'Australia': 'AU',
    'Central African Republic': 'CF',
    'Slovenia': 'SI',
    'Austria': 'AT',
    'Brazil': 'BR',
    'Switzerland': 'CH',
    'Costa Rica': 'CR',
    'Colombia': 'CO',
    'Latvia': 'LV',
    'Zambia': 'ZM',
    'Gabon': 'GA',
    'Romania': 'RO',
    'Lithuania': 'LT',
    'United Kingdom': 'GB',
    'Ecuador': 'EC',
    'Croatia': 'HR',
    'Chile': 'CL',
    'France': 'FR',
    'Estonia': 'EE',
    'Bolivia': 'BO',
    'Panama': 'PA',
    'Ireland': 'IE',
    'Denmark': 'DK',
    'Malawi': 'MW',
    'Spain': 'ES',
    'Peru': 'PE',
    'Germany': 'DE',
    'Slovakia': 'SK',
    'Congo Democratic Republic': 'CD',
    'Albania': 'AL',
    'Japan': 'JP',
    'Venezuela': 'VE',
    'Uruguay': 'UY',
    'Portugal': 'PT',
    'Uganda': 'UG',
    'Laos': 'LA',
    'Namibia': 'NA',
    'United States': 'US',
    'Nepal': 'NP',
    'Congo Republic': 'CG',
    'Greece': 'GR',
    'Netherlands': 'NL',
    'Russia': 'RU',
    'Italy': 'IT',
    'Mozambique': 'MZ',
    'Czechia': 'CZ',
    'Hungary': 'HU',
    'Nicaragua': 'NI',
    'Equatorial Guinea': 'GQ',
    'Poland': 'PL',
    'Tajikistan': 'TJ',
    'Bulgaria': 'BG',
    'Belgium': 'BE',
    'Mongolia': 'MN',
    'Honduras': 'HN',
    'Georgia': 'GE',
    'Ethiopia': 'ET',
    'Cameroon': 'CM',
    'Mali': 'ML',
    'Kyrgyzstan': 'KG',
    'Malaysia': 'MY',
    'Niger': 'NE',
    'Papua New Guinea': 'PG',
    'Mexico': 'MX',
    'Argentina': 'AR',
    'Kazakhstan': 'KZ',
    'Guinea': 'GN',
    'Botswana': 'BW',
    'Burundi': 'BI',
    'Cambodia': 'KH',
    'Belarus': 'BY',
    'Zimbabwe': 'ZW',
    'North Macedonia': 'MK',
    'Serbia': 'RS',
    'Timor-Leste': 'TL',
    'Sierra Leone': 'SL',
    'United Arab Emirates': 'AE',
    'Myanmar': 'MM',
    'Burkina Faso': 'BF',
    'South Korea': 'KR',
    'Dominican Republic': 'DO',
    'Rwanda': 'RW',
    'Thailand': 'TH',
    'Chad': 'TD',
    'Angola': 'AO',
    'Kenya': 'KE',
    'Ghana': 'GH',
    'Indonesia': 'ID',
    'Tanzania': 'TZ',
    'Armenia': 'AM',
    'Ukraine': 'UA',
    'Guinea Bissau': 'GW',
    'Senegal': 'SN',
    'Jamaica': 'JM',
    'Benin': 'BJ',
    'Bosnia and Herzegovina': 'BA',
    'Morocco': 'MA',
    'Cuba': 'CU',
    'Trinidad and Tobago': 'TT',
    'Sri Lanka': 'LK',
    'Lesotho': 'LS',
    'Philippines': 'PH',
    'Togo': 'TG',
    'El Salvador': 'SV',
    'Kuwait': 'KW',
    'Guatemala': 'GT',
    'Nigeria': 'NG',
    'Vietnam': 'VN',
    "Cote d'Ivoire": 'CI',
    'South Africa': 'ZA',
    'Sudan': 'SD',
    'Turkey': 'TR',
    'Azerbaijan': 'AZ',
    'Liberia': 'LR',
    'Madagascar': 'MG',
    'South Sudan': 'SS',
    'Cyprus': 'CY',
    'Singapore': 'SG',
    'Jordan': 'JO',
    'Israel': 'IL',
    'Moldova': 'MD',
    'Egypt': 'EG',
    'Iraq': 'IQ',
    'Bahrain': 'BH',
    'Bangladesh': 'BD',
    'Gambia': 'GM',
    'Saudi Arabia': 'SA',
    'Somalia': 'SO',
    'Mauritania': 'MR',
    'China': 'CN',
    'Oman': 'OM',
    'Pakistan': 'PK',
    'Eswatini': 'SZ',
    'India': 'IN',
    'Palestine': 'PS',
    'Iran': 'IR',
    'Qatar': 'QA',
    'Tunisia': 'TN',
    'Turkmenistan': 'TM',
    'Afghanistan': 'AF',
    'Algeria': 'DZ',
    'Haiti': 'HT',
    'Uzbekistan': 'UZ',
    'Mauritius': 'MU',
    'Lebanon': 'LB',
    'Yemen': 'YE',
    'Libya': 'LY',
    'Syria': 'SY'
}

sri['code'] = sri['country'].map(country_code_map)
sri

,country,inclusion,social_cohesion,state_capacity,individual_capabilities_resources,environment_ecology,economy,civic_space,capacity_score,code
0,New Zealand,"9,1","7,2","8,6","8,6","7,2","7,1","9,2","8,1",NZ
1,Norway,"9,2","8,1","8,9","9,2","7,2","6,8","9,4","8,4",NO
2,Sweden,"9,0","7,8","8,4","9,0","7,0","7,6","9,5","8,3",SE
3,Finland,"9,0","7,7","8,7","9,2","6,8","7,2","9,3","8,3",FI
4,Canada,"8,9","6,8","8,1","8,9","6,8","6,9","8,6","7,8",CA
...,...,...,...,...,...,...,...,...,...,...
149,Mauritius,"6,7","6,3","6,9","7,3","3,7","5,6","7,6","6,3",MU
150,Lebanon,"4,6","3,7","4,2","7,2","3,6","4,9","5,8","4,9",LB
151,Yemen,"2,4","2,8","2,8","3,2","3,6","3,3","2,2","2,9",YE
152,Libya,"4,5","4,5","3,7","5,4","2,9","3,2","3,9","4,0",LY
153,Syria,"3,1","2,1","4,1","4,8","2,9","3,8","2,3","3,3",SY

In [43]:
sri.to_csv('./data/to use/sri_2022.csv')