In [45]:
import pandas as pd

In [46]:
sub_sust_score = pd.read_csv('../sustainable_development_report/select/select_sustainability_scores.csv', sep=';')

In [47]:
energy_environment = pd.read_csv('../GlobalEconomy dataset/data/energy_and_environment.csv')

In [48]:
sub_sust_score

,code,country,year,sdg6_freshwat,sdg6_wastewat,sdg6_scarcew,sdg7_elecac,sdg7_cleanfuel,sdg7_co2twh,sdg7_renewcon,...,sdg12_so2import,sdg12_explastic,sdg12_mswrecycl,sdg13_co2gcp,sdg13_co2import,sdg13_co2export,sdg13_ecr,sdg15_cpta,sdg15_cpfa,sdg15_redlist
0,AFG,Afghanistan,2000,55.0,NaN,NaN,2.0,6.0,"1,61",7.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,1
1,AFG,Afghanistan,2001,55.0,NaN,NaN,4.0,7.0,"1,34",6.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,1
2,AFG,Afghanistan,2002,55.0,NaN,NaN,9.0,8.0,"1,56",6.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,1
3,AFG,Afghanistan,2003,55.0,NaN,NaN,15.0,10.0,"1,28",6.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,1
4,AFG,Afghanistan,2004,55.0,NaN,NaN,20.0,11.0,"1,02",7.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4627,ZWE,Zimbabwe,2019,35.0,NaN,NaN,47.0,30.0,"1,29",9.0,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,81.0,82.0,1
4628,ZWE,Zimbabwe,2020,NaN,37.0,NaN,53.0,30.0,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,81.0,82.0,1
4629,ZWE,Zimbabwe,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,1.0,NaN,30.0,NaN,81.0,82.0,1
4630,ZWE,Zimbabwe,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81.0,82.0,1
4631,ZWE,Zimbabwe,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [49]:
glob_sust_score = pd.read_csv('../sustainable_development_report/select/global_sdg_index.csv', sep=';')

In [50]:
glob_sust_score.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4140 entries, 0 to 4139
Data columns (total 22 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   code                               4140 non-null   object
 1   Country                            4140 non-null   object
 2   year                               4140 non-null   int64
 3   population                         3818 non-null   float64
 4   SDG Index Score                    4140 non-null   object
 5   1no_poverty                        3795 non-null   object
 6   2no_hunger                         4140 non-null   object
 7   3health_wellbeing                  4140 non-null   object
 8   4quality_education                 4140 non-null   object
 9   5gender_equality                   4140 non-null   object
 10  6cleanwater_sanitation             4140 non-null   object
 11  7affordable_clean_energy           4140 non-null   object
 12  8work_economy_growth               4140 non-null   object
 13  9industry_innov_infrast            4140 non-null   object
 14  10reduced_inequalities             3749 non-null   object
 15  11cities_communities               4140 non-null   object
 16  12consumption_production           4140 non-null   object
 17  13climate                          4140 non-null   object
 18  14life_below_water                 3197 non-null   object
 19  15life_on_land                     4140 non-null   object
 20  16peace_justice_stroninstitutions  4140 non-null   object
 21  17partnership_for_goals            4140 non-null   object
dtypes: float64(1), int64(1), object(20)
memory usage: 711.7+ KB

In [51]:
# List of columns to be converted
columns_to_convert = [
    'SDG Index Score', '1no_poverty', '2no_hunger', '3health_wellbeing', '4quality_education',
    '5gender_equality', '6cleanwater_sanitation', '7affordable_clean_energy', '8work_economy_growth',
    '9industry_innov_infrast', '10reduced_inequalities', '11cities_communities', '12consumption_production',
    '13climate', '14life_below_water', '15life_on_land', '16peace_justice_stroninstitutions', '17partnership_for_goals'
]

# Replace commas with dots and convert to float for each column
for col in columns_to_convert:
    glob_sust_score[col] = glob_sust_score[col].str.replace(',', '.').astype('float64')

In [52]:
glob_sust_score.columns

Index(['code', 'Country', 'year', 'population', 'SDG Index Score',
       '1no_poverty', '2no_hunger', '3health_wellbeing', '4quality_education',
       '5gender_equality', '6cleanwater_sanitation',
       '7affordable_clean_energy', '8work_economy_growth',
       '9industry_innov_infrast', '10reduced_inequalities',
       '11cities_communities', '12consumption_production', '13climate',
       '14life_below_water', '15life_on_land',
       '16peace_justice_stroninstitutions', '17partnership_for_goals'],
      dtype='object')

In [53]:
glob_sust_score = glob_sust_score.loc[glob_sust_score['year']<=2020]

In [54]:
glob_sust_score.to_csv('./sustainability/glob_sust_score.csv')

In [55]:
denmark_score_sust = pd.read_csv('./sustainability/denmarl_sust_score.csv', sep=';')

In [56]:
denmark_score_sust.set_index('year', inplace=True)

In [57]:
denmark_score_sust

,sdg_index_score,1no_poverty,2no_hunger,3health_wellbeing,4quality_education,5gender_equality,6cleanwater_sanitation,7affordable_clean_energy,8work_economy_growth,9industry_innov_infrast,10reduced_inequalities,11cities_communities,12consumption_production,13climate,14life_below_water,15life_on_land,16peace_justice_stroninstitutions,17partnership_for_goals
year,,,,,,,,,,,,,,,,,,
2000,81.6,99.3,75.6,89.5,99.2,84.3,91.7,72.3,87.6,71.7,100.0,90.6,34.7,56.0,71.4,92.5,92.7,77.7
2001,81.6,99.3,75.1,89.6,99.1,84.4,92.1,72.6,87.6,72.8,100.0,90.6,34.1,55.5,71.7,92.4,92.8,78.0
2002,82.0,99.3,75.7,89.9,99.1,84.7,92.4,73.4,87.7,76.3,100.0,90.6,34.1,55.7,71.2,92.4,92.8,78.0
2003,82.2,99.3,76.2,90.5,99.1,84.8,92.4,74.2,87.1,78.3,100.0,90.6,33.9,54.2,74.0,92.5,92.8,78.0
2004,82.3,99.3,75.7,91.0,98.0,84.9,92.5,74.9,87.1,78.7,100.0,90.6,33.5,55.9,74.3,92.5,92.8,78.0
2005,82.5,99.3,74.2,91.2,98.2,84.3,92.5,75.5,87.3,78.8,100.0,90.7,33.4,57.1,75.6,92.5,93.2,78.0
2006,82.2,99.3,73.5,91.1,98.4,84.3,92.8,75.6,87.9,79.4,100.0,90.7,33.5,54.7,73.2,92.5,93.0,78.0
2007,82.4,99.3,72.8,90.4,98.9,84.9,93.0,76.4,87.8,79.6,100.0,89.5,33.5,56.3,74.2,92.6,94.2,78.0
2008,82.1,99.3,73.4,90.6,98.8,85.0,92.1,76.7,87.7,82.5,100.0,86.2,32.9,57.4,70.3,92.6,92.3,78.0
2009,82.5,99.3,76.0,90.9,97.7,85.0,92.4,77.4,86.5,85.4,100.0,86.6,35.6,58.2,68.2,92.8,92.0,78.0
2010,82.8,99.3,73.2,92.1,97.8,85.0,91.4,78.6,85.7,90.1,100.0,89.5,35.6,58.1,68.0,92.8,91.8,78.0
2011,83.3,99.1,72.7,92.7,98.9,85.6,91.1,80.0,85.7,93.2,100.0,89.3,35.9,58.7,70.9,93.0,91.9,78.0
2012,84.0,99.2,74.6,93.2,98.0,85.6,91.9,81.3,85.7,95.0,99.6,89.4,36.2,61.4,72.6,92.9,92.9,78.0
2013,83.9,98.8,73.5,93.1,98.4,86.7,90.2,81.9,85.9,96.4,98.6,89.9,36.7,60.4,73.4,92.9,92.2,78.0
2014,83.9,99.0,74.1,93.1,96.7,85.1,90.3,83.6,86.1,96.4,98.7,89.4,36.4,61.4,73.0,92.9,91.4,78.0
2015,84.6,99.1,74.0,94.0,97.0,85.2,91.4,84.8,86.5,97.0,98.1,91.1,37.5,62.6,76.3,92.9,93.2,78.0
2016,84.7,99.1,72.1,94.4,98.6,85.7,90.9,84.5,86.7,96.9,98.7,92.1,37.6,61.7,76.8,92.9,93.2,78.0
2017,84.5,99.4,74.0,95.3,96.4,85.7,90.9,86.4,86.8,96.3,97.4,91.7,37.5,62.7,71.7,92.9,92.7,78.5
2018,84.3,99.3,68.3,95.1,98.3,85.7,89.6,86.0,87.0,96.8,98.4,92.6,37.2,59.2,72.3,92.8,93.9,81.1
2019,85.0,99.2,72.1,95.6,97.7,86.4,90.7,87.7,87.1,96.6,98.2,92.2,37.3,60.3,75.9,92.8,94.5,81.0
2020,85.1,99.2,72.1,95.3,99.3,86.8,90.7,87.7,86.7,96.6,98.2,91.8,37.3,61.1,76.1,92.8,93.2,81.3
2021,85.8,99.2,71.0,95.6,99.3,86.7,90.7,87.7,87.1,97.0,98.2,95.1,44.6,60.8,76.3,92.8,93.8,82.5
2022,85.7,99.2,71.0,95.4,99.3,87.0,90.7,87.7,87.6,97.0,98.2,93.0,44.6,60.8,76.3,92.8,93.8,82.1

In [59]:
glob_sust_score.columns

Index(['code', 'Country', 'year', 'population', 'SDG Index Score',
       '1no_poverty', '2no_hunger', '3health_wellbeing', '4quality_education',
       '5gender_equality', '6cleanwater_sanitation',
       '7affordable_clean_energy', '8work_economy_growth',
       '9industry_innov_infrast', '10reduced_inequalities',
       '11cities_communities', '12consumption_production', '13climate',
       '14life_below_water', '15life_on_land',
       '16peace_justice_stroninstitutions', '17partnership_for_goals'],
      dtype='object')

In [60]:
glob_sust_score.columns = ['code', 'country', 'year', 'population', 'sdg_index_score',
       '1no_poverty', '2no_hunger', '3health_wellbeing', '4quality_education',
       '5gender_equality', '6cleanwater_sanitation',
       '7affordable_clean_energy', '8work_economy_growth',
       '9industry_innov_infrast', '10reduced_inequalities',
       '11cities_communities', '12consumption_production', '13climate',
       '14life_below_water', '15life_on_land',
       '16peace_justice_stroninstitutions', '17partnership_for_goals']

In [61]:
glob_sust_score

,code,country,year,population,sdg_index_score,1no_poverty,2no_hunger,3health_wellbeing,4quality_education,5gender_equality,...,8work_economy_growth,9industry_innov_infrast,10reduced_inequalities,11cities_communities,12consumption_production,13climate,14life_below_water,15life_on_land,16peace_justice_stroninstitutions,17partnership_for_goals
0,AFG,Afghanistan,2000,19669913.0,36.0,28.8,27.3,19.2,1.6,20.8,...,38.5,5.2,NaN,25.8,94.7,99.4,NaN,51.9,39.2,34.2
1,AFG,Afghanistan,2001,19416052.0,36.3,28.8,30.6,19.4,1.6,20.8,...,38.5,5.2,NaN,25.8,94.5,99.4,NaN,51.9,39.2,34.2
2,AFG,Afghanistan,2002,19961213.0,36.3,28.8,30.7,19.7,1.6,20.8,...,38.4,5.2,NaN,26.1,94.1,99.4,NaN,51.8,39.2,34.2
3,AFG,Afghanistan,2003,22039300.0,36.7,28.8,32.5,19.9,1.6,20.8,...,38.4,5.2,NaN,26.5,94.4,99.4,NaN,51.8,39.2,34.2
4,AFG,Afghanistan,2004,23250960.0,37.1,28.8,32.1,21.1,1.6,20.8,...,38.5,5.2,NaN,26.8,94.8,99.4,NaN,51.8,39.2,34.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4133,ZWE,Zimbabwe,2016,14303586.0,56.1,29.1,43.7,36.9,60.8,75.8,...,60.6,25.4,37.0,76.1,93.5,94.8,NaN,78.0,46.2,48.6
4134,ZWE,Zimbabwe,2017,14601823.0,56.4,27.6,46.4,38.5,59.6,77.2,...,63.6,25.7,32.4,75.7,94.5,94.9,NaN,78.0,44.9,51.9
4135,ZWE,Zimbabwe,2018,14900379.0,55.9,26.4,46.6,39.8,57.9,76.7,...,63.8,23.5,32.4,79.2,94.6,94.1,NaN,76.4,45.5,45.6
4136,ZWE,Zimbabwe,2019,15203989.0,53.7,21.4,46.0,40.6,60.6,77.0,...,62.8,23.8,24.0,58.6,94.6,94.2,NaN,76.4,44.0,44.5
4137,ZWE,Zimbabwe,2020,15505226.0,54.3,20.1,47.2,41.5,62.0,77.0,...,62.9,25.4,24.0,60.0,94.6,94.3,NaN,76.4,44.6,46.0