In [1]:
import pandas as pd

In [2]:
sustainability = pd.read_csv('./data/glob_sust_score.csv')

In [3]:
sustainability = sustainability.drop(columns=['Unnamed: 0','Country'])

In [4]:
sri = pd.read_csv('./data/sri_2022.csv')
fragile_index = pd.read_csv('./data/fragile_index.csv')

In [5]:
top28_countries = ['USA', 'Spain', 'France', 'United Kingdom', 
                   'Germany', 'Italy', 'Thailand', 'Turkey', 
                   'China', 'China', 'China', 'Canada', 'Japan', 
                   'Austria', 'Netherlands', 'Malaysia', 'Mexico', 
                   'Greece', 'United Arab Emirates', 'Singapore', 
                   'Russia', 'Poland', 'Saudi Arabia', 'Croatia', 
                   'South Africa', 'Denmark', 'Czechia', 'Hungary', 
                   'Ukraine', 'Slovakia']

In [6]:
sustainability

,code,year,population,SDG Index Score,1no_poverty,2no_hunger,3health_wellbeing,4quality_education,5gender_equality,6cleanwater_sanitation,...,8work_economy_growth,9industry_innov_infrast,10reduced_inequalities,11cities_communities,12consumption_production,13climate,14life_below_water,15life_on_land,16peace_justice_stroninstitutions,17partnership_for_goals
0,AFG,2000,19669913.0,36.0,28.8,27.3,19.2,1.6,20.8,32.4,...,38.5,5.2,NaN,25.8,94.7,99.4,NaN,51.9,39.2,34.2
1,AFG,2001,19416052.0,36.3,28.8,30.6,19.4,1.6,20.8,32.4,...,38.5,5.2,NaN,25.8,94.5,99.4,NaN,51.9,39.2,34.2
2,AFG,2002,19961213.0,36.3,28.8,30.7,19.7,1.6,20.8,32.7,...,38.4,5.2,NaN,26.1,94.1,99.4,NaN,51.8,39.2,34.2
3,AFG,2003,22039300.0,36.7,28.8,32.5,19.9,1.6,20.8,33.0,...,38.4,5.2,NaN,26.5,94.4,99.4,NaN,51.8,39.2,34.2
4,AFG,2004,23250960.0,37.1,28.8,32.1,21.1,1.6,20.8,33.3,...,38.5,5.2,NaN,26.8,94.8,99.4,NaN,51.8,39.2,34.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3775,ZWE,2016,14303586.0,56.1,29.1,43.7,36.9,60.8,75.8,53.0,...,60.6,25.4,37.0,76.1,93.5,94.8,NaN,78.0,46.2,48.6
3776,ZWE,2017,14601823.0,56.4,27.6,46.4,38.5,59.6,77.2,52.8,...,63.6,25.7,32.4,75.7,94.5,94.9,NaN,78.0,44.9,51.9
3777,ZWE,2018,14900379.0,55.9,26.4,46.6,39.8,57.9,76.7,51.6,...,63.8,23.5,32.4,79.2,94.6,94.1,NaN,76.4,45.5,45.6
3778,ZWE,2019,15203989.0,53.7,21.4,46.0,40.6,60.6,77.0,51.3,...,62.8,23.8,24.0,58.6,94.6,94.2,NaN,76.4,44.0,44.5
3779,ZWE,2020,15505226.0,54.3,20.1,47.2,41.5,62.0,77.0,51.1,...,62.9,25.4,24.0,60.0,94.6,94.3,NaN,76.4,44.6,46.0

In [7]:
sustainability.columns = ['code', 'year', 'population', 'sdg_index_score',
       '1no_poverty', '2no_hunger', '3health_wellbeing', '4quality_education',
       '5gender_equality', '6cleanwater_sanitation',
       '7affordable_clean_energy', '8work_economy_growth',
       '9industry_innov_infrast', '10reduced_inequalities',
       '11cities_communities', '12consumption_production', '13climate',
       '14life_below_water', '15life_on_land',
       '16peace_justice_stroninstitutions', '17partnership_for_goals']

In [8]:
columns_for_score = ['3health_wellbeing', '7affordable_clean_energy','8work_economy_growth',
                     '9industry_innov_infrast','10reduced_inequalities','11cities_communities',
                     '13climate']

sustainability['tourism_score'] = sustainability[columns_for_score].mean(axis=1)

In [9]:
sustainability_tourism = sustainability[['code','year','tourism_score']]

In [10]:
sustainability_tourism = sustainability_tourism.groupby('code')['tourism_score'].mean().reset_index()

In [11]:
sustainability_tourism_rank = sustainability_tourism.sort_values(by='tourism_score', ascending=False)

In [12]:
sustainability_tourism_rank[sustainability_tourism_rank['code']=='USA']

    code  tourism_score
158  USA      73.485034

In [13]:
sri = sri.drop(columns=['Unnamed: 0'])
fragile_index = fragile_index.drop(columns=['Unnamed: 0'])

In [14]:
#fragile_index = fragile_index[['code','year','fragile_state_index']]

In [15]:
fragile_index[fragile_index['code']=='USA']

,country,code,year,fragile_state_index,security_threats_index,factionalized_elites_index,group_grievance_index,economic_decline_index,uneven_economic_development,human_flight_and_brain_drain,state_legitimacy_index,public_services_index,human_rights_and_rule_of_law_index,demographic_pressures,refugees_and_displaced_persons_index,external_interventions_index
2872,USA,USA,2007,33.6,1.3,1.7,3.2,1.8,5.8,1.0,2.8,1.4,4.6,3.5,5.5,1.0
2873,USA,USA,2008,32.8,1.3,2.0,3.2,2.3,5.5,1.0,3.0,1.8,4.2,3.5,4.0,1.0
2874,USA,USA,2009,34.0,1.4,2.5,3.3,2.9,5.3,1.0,3.0,2.3,4.0,3.1,3.7,1.5
2875,USA,USA,2010,35.3,1.6,3.3,3.4,4.0,5.4,1.1,2.5,2.5,3.7,3.1,3.2,1.5
2876,USA,USA,2011,34.8,1.6,3.6,3.6,3.7,5.4,1.1,2.2,2.7,3.3,3.4,2.9,1.3
2877,USA,USA,2012,34.8,1.9,3.6,3.9,3.4,5.1,1.3,2.6,2.7,3.5,3.3,2.6,1.0
2878,USA,USA,2013,33.5,2.2,3.9,4.2,3.2,4.8,1.0,2.3,2.4,3.2,3.0,2.3,1.0
2879,USA,USA,2014,35.4,2.7,4.0,4.5,3.1,4.5,1.2,2.4,2.5,3.5,3.3,2.4,1.3
2880,USA,USA,2015,35.4,2.8,4.0,5.0,2.8,4.8,1.5,2.4,2.1,3.7,3.0,2.1,1.1
2881,USA,USA,2016,34.0,2.9,4.3,5.1,2.5,4.5,1.4,2.1,1.8,3.4,3.0,2.1,0.9
2882,USA,USA,2017,35.6,3.2,5.3,6.0,2.4,4.3,1.7,1.9,1.6,3.2,2.8,2.0,1.2
2883,USA,USA,2018,37.7,3.5,5.8,6.1,2.3,4.0,2.2,2.4,1.3,3.3,3.3,2.1,1.5
2884,USA,USA,2019,38.0,3.5,5.8,6.1,2.1,3.7,1.9,2.6,1.2,3.8,3.3,2.4,1.6
2885,USA,USA,2020,38.3,3.8,6.8,6.2,1.8,3.4,1.8,2.9,1.2,3.9,3.0,2.1,1.3
2886,USA,USA,2021,44.6,4.3,7.3,6.5,2.1,3.7,1.8,3.5,2.7,4.4,5.0,2.3,1.0
2887,USA,USA,2022,46.6,5.0,7.3,6.8,1.8,3.7,1.8,4.5,2.5,4.5,5.5,2.5,0.7
2888,USA,USA,2023,45.3,4.7,7.3,6.5,2.1,4.0,1.7,4.2,2.2,NaN,5.2,2.2,NaN

In [16]:
fragile_index

,country,code,year,fragile_state_index,security_threats_index,factionalized_elites_index,group_grievance_index,economic_decline_index,uneven_economic_development,human_flight_and_brain_drain,state_legitimacy_index,public_services_index,human_rights_and_rule_of_law_index,demographic_pressures,refugees_and_displaced_persons_index,external_interventions_index
0,Afghanistan,AFG,2007,102.3,9.0,8.5,9.1,8.3,8.0,7.0,8.8,8.0,8.2,8.5,8.9,10.0
1,Afghanistan,AFG,2008,105.4,9.6,8.8,9.5,8.5,8.1,7.0,9.2,8.3,8.4,9.1,8.9,10.0
2,Afghanistan,AFG,2009,108.2,9.9,9.1,9.6,8.3,8.4,7.2,9.8,8.9,8.8,9.3,8.9,10.0
3,Afghanistan,AFG,2010,109.3,9.7,9.4,9.7,8.3,8.2,7.2,10.0,8.9,9.2,9.5,9.2,10.0
4,Afghanistan,AFG,2011,107.5,9.8,9.4,9.3,8.0,8.4,7.2,9.7,8.5,8.8,9.1,9.3,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2986,Zimbabwe,ZWE,2019,99.5,8.8,10.0,6.7,8.1,7.9,7.3,9.4,8.6,8.2,9.0,8.2,7.3
2987,Zimbabwe,ZWE,2020,99.2,8.5,10.0,6.4,8.6,7.6,7.0,9.1,8.7,8.3,9.3,8.5,7.2
2988,Zimbabwe,ZWE,2021,99.1,8.6,10.0,6.1,9.4,7.7,7.1,8.8,9.0,8.0,9.3,8.2,6.9
2989,Zimbabwe,ZWE,2022,97.8,8.7,9.9,5.8,9.1,7.7,7.0,8.9,8.7,8.1,9.0,7.9,7.0
2990,Zimbabwe,ZWE,2023,96.9,8.4,10.0,5.9,9.2,7.8,7.1,8.9,8.8,NaN,8.7,7.6,NaN

In [17]:
sustainability['code'].unique()

array(['AFG', 'ALB', 'DZA', 'AGO', 'ARG', 'ARM', 'AUS', 'AUT', 'AZE',
       'BHS', 'BHR', 'BGD', 'BRB', 'BLR', 'BEL', 'BLZ', 'BEN', 'BTN',
       'BOL', 'BIH', 'BWA', 'BRA', 'BRN', 'BGR', 'BFA', 'BDI', 'CPV',
       'KHM', 'CMR', 'CAN', 'CAF', 'TCD', 'CHL', 'CHN', 'COL', 'COM',
       'COD', 'COG', 'CRI', 'CIV', 'HRV', 'CUB', 'CYP', 'CZE', 'DNK',
       'DJI', 'DOM', '_E_S_Asia', '_E_Euro_Asia', 'ECU', 'EGY', 'SLV',
       'EST', 'SWZ', 'ETH', 'FJI', 'FIN', 'FRA', 'GAB', 'GMB', 'GEO',
       'DEU', 'GHA', 'GRC', 'GTM', 'GIN', 'GUY', 'HTI', '_HIC', 'HND',
       'HUN', 'ISL', 'IND', 'IDN', 'IRN', 'IRQ', 'IRL', 'ISR', 'ITA',
       'JAM', 'JPN', 'JOR', 'KAZ', 'KEN', 'KOR', 'KWT', 'KGZ', 'LAO',
       '_LAC', 'LVA', 'LBN', 'LSO', 'LBR', 'LTU', '_LIC_LMIC', '_LMIC',
       '_LIC', 'LUX', 'MDG', 'MWI', 'MYS', 'MDV', 'MLI', 'MLT', 'MRT',
       'MUS', 'MEX', '_MENA', 'MDA', 'MNG', 'MNE', 'MAR', 'MOZ', 'MMR',
       'NAM', 'NPL', 'NLD', 'NZL', 'NIC', 'NER', 'NGA', 'MKD', 'NOR',
       '_Oceania', '_OECD', 'OMN', 'PAK', 'PAN', 'PNG', 'PRY', 'PER',
       'PHL', 'POL', 'PRT', 'QAT', 'ROU', 'RUS', 'RWA', 'STP', 'SAU',
       'SEN', 'SRB', 'SLE', 'SGP', 'SVK', 'SVN', '_SIDS', 'SOM', 'ZAF',
       'SSD', 'ESP', 'LKA', '_Africa', 'SDN', 'SUR', 'SWE', 'CHE', 'SYR',
       'TJK', 'TZA', 'THA', 'TGO', 'TTO', 'TUN', 'TUR', 'TKM', 'UGA',
       'UKR', 'ARE', 'GBR', 'USA', '_UMIC', 'URY', 'UZB', 'VEN', 'VNM',
       '_World', 'YEM', 'ZMB', 'ZWE'], dtype=object)

In [18]:
fragile_index['fragile_state_score'] = (120 - fragile_index['fragile_state_index']) * (100 / 119)

In [19]:
fragile_index_22 = fragile_index[fragile_index['year']>=2020]
#fragile_index_22 = fragile_index_22.drop(columns=['year', 'fragile_state_index'])

In [20]:
fragile_index_22

,country,code,year,fragile_state_index,security_threats_index,factionalized_elites_index,group_grievance_index,economic_decline_index,uneven_economic_development,human_flight_and_brain_drain,state_legitimacy_index,public_services_index,human_rights_and_rule_of_law_index,demographic_pressures,refugees_and_displaced_persons_index,external_interventions_index,fragile_state_score
13,Afghanistan,AFG,2020,102.9,9.9,8.9,7.5,8.3,7.7,7.5,9.0,9.5,7.6,9.0,9.3,8.6,14.369748
14,Afghanistan,AFG,2021,102.1,10.0,8.6,7.2,9.2,8.1,7.0,8.7,9.8,7.4,9.0,8.8,8.3,15.042017
15,Afghanistan,AFG,2022,105.9,10.0,8.7,8.2,9.3,8.2,8.0,NaN,9.9,8.4,9.1,8.9,8.0,11.848739
16,Afghanistan,AFG,2023,106.6,9.7,8.7,8.3,9.6,8.2,8.5,9.4,10.0,NaN,9.2,8.6,NaN,11.260504
30,Albania,ALB,2020,58.8,5.1,6.2,4.4,5.8,2.7,8.1,5.8,3.9,3.9,3.6,2.9,6.4,51.428571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2973,Zambia,ZMB,2023,81.8,3.9,5.6,5.9,8.2,9.1,6.3,6.7,8.1,NaN,9.4,4.9,NaN,32.100840
2987,Zimbabwe,ZWE,2020,99.2,8.5,10.0,6.4,8.6,7.6,7.0,9.1,8.7,8.3,9.3,8.5,7.2,17.478992
2988,Zimbabwe,ZWE,2021,99.1,8.6,10.0,6.1,9.4,7.7,7.1,8.8,9.0,8.0,9.3,8.2,6.9,17.563025
2989,Zimbabwe,ZWE,2022,97.8,8.7,9.9,5.8,9.1,7.7,7.0,8.9,8.7,8.1,9.0,7.9,7.0,18.655462
2990,Zimbabwe,ZWE,2023,96.9,8.4,10.0,5.9,9.2,7.8,7.1,8.9,8.8,NaN,8.7,7.6,NaN,19.411765

In [21]:
fragile_index_22 = fragile_index_22[['code','country','fragile_state_score']]

In [22]:
fragile_index_22['code'].unique()

array(['AFG', 'ALB', 'DZA', 'AGO', 'ATG', 'ARG', 'ARM', 'AUS', 'AUT',
       'AZE', 'BHS', 'BHR', 'BGD', 'BRB', 'BLR', 'BEL', 'BLZ', 'BEN',
       'BTN', 'BOL', 'BIH', 'BWA', 'BRA', 'BRN', 'BGR', 'BFA', 'MMR',
       'BDI', 'KHM', 'CMR', 'CAN', 'CPV', 'CAF', 'TCD', 'CHL', 'CHN',
       'COL', 'COM', 'CRC', 'HRV', 'CUB', 'CYP', 'CZE', 'COD', 'DNK',
       'DJI', 'DOM', 'ECU', 'EGY', 'SLV', 'GNQ', 'ERI', 'EST', 'ETH',
       'FJI', 'FIN', 'FRA', 'GAB', 'GMB', 'GEO', 'DEU', 'GHA', 'GRC',
       'GRD', 'GTM', 'GIN', 'GNB', 'GUY', 'HTI', 'HND', 'HUN', 'ISL',
       'IND', 'IDN', 'IRN', 'IRQ', 'IRL', 'ISR', 'ITA', 'CIV', 'JAM',
       'JPN', 'JOR', 'KAZ', 'KEN', 'KWT', 'KGZ', 'LAO', 'LVA', 'LBN',
       'LSO', 'LBR', 'LBY', 'LTU', 'LUX', 'MAC', 'MDG', 'MWI', 'MYS',
       'MDV', 'MLI', 'MLT', 'MRT', 'MUS', 'MEX', 'FSM', 'MDA', 'MNG',
       'MNE', 'MAR', 'MOZ', 'NAM', 'NPL', 'NLD', 'NZL', 'NIC', 'NER',
       'NGA', 'PRK', 'MKD', 'NOR', 'OMN', 'PAK', 'PS', 'PAN', 'PNG',
       'PRY', 'PER', 'PHL', 'POL', 'PRT', 'QAT', 'COG', 'ROU', 'RUS',
       'RWA', 'WSM', 'STP', 'SAU', 'SEN', 'SRB', 'SYC', 'SLE', 'SGP',
       'SVK', 'SVN', 'SLB', 'SOM', 'ZAF', 'KOR', 'ESP', 'LKA', 'SDN',
       'SUR', 'SWZ', 'SWE', 'CHE', 'SYR', 'TJK', 'TZA', 'THA', 'TGO',
       'TTO', 'TUN', 'TUR', 'TKM', 'UGA', 'UKR', 'ARE', 'GBR', 'URY',
       'USA', 'UZB', 'VEN', 'VNM', 'YEM', 'ZMB', 'ZWE'], dtype=object)

In [23]:
columns_to_convert = ['inclusion', 'social_cohesion', 'state_capacity',
                      'individual_capabilities_resources', 'environment_ecology', 
                      'economy', 'civic_space', 'capacity_score']

# Replace commas with dots and convert to float
sri[columns_to_convert] = sri[columns_to_convert].apply(lambda x: x.str.replace(',', '.').astype(float))

# Calculate the mean of the specified columns to create the 'sri_score' column
sri['sri_score'] = sri[columns_to_convert].mean(axis=1)

In [24]:
sri['sri_score'] = sri['sri_score']*10

In [25]:
sri

,country,inclusion,social_cohesion,state_capacity,individual_capabilities_resources,environment_ecology,economy,civic_space,capacity_score,code,sri_score
0,New Zealand,9.1,7.2,8.6,8.6,7.2,7.1,9.2,8.1,NZ,81.375
1,Norway,9.2,8.1,8.9,9.2,7.2,6.8,9.4,8.4,NO,84.000
2,Sweden,9.0,7.8,8.4,9.0,7.0,7.6,9.5,8.3,SE,83.250
3,Finland,9.0,7.7,8.7,9.2,6.8,7.2,9.3,8.3,FI,82.750
4,Canada,8.9,6.8,8.1,8.9,6.8,6.9,8.6,7.8,CA,78.500
...,...,...,...,...,...,...,...,...,...,...,...
149,Mauritius,6.7,6.3,6.9,7.3,3.7,5.6,7.6,6.3,MU,63.000
150,Lebanon,4.6,3.7,4.2,7.2,3.6,4.9,5.8,4.9,LB,48.625
151,Yemen,2.4,2.8,2.8,3.2,3.6,3.3,2.2,2.9,YE,29.000
152,Libya,4.5,4.5,3.7,5.4,2.9,3.2,3.9,4.0,LY,40.125
153,Syria,3.1,2.1,4.1,4.8,2.9,3.8,2.3,3.3,SY,33.000

In [26]:
sri[sri['code']=='USA']

Empty DataFrame
Columns: [country, inclusion, social_cohesion, state_capacity, individual_capabilities_resources, environment_ecology, economy, civic_space, capacity_score, code, sri_score]
Index: []

In [27]:
fragile_index[fragile_index['country']=='Iceland']

,country,code,year,fragile_state_index,security_threats_index,factionalized_elites_index,group_grievance_index,economic_decline_index,uneven_economic_development,human_flight_and_brain_drain,state_legitimacy_index,public_services_index,human_rights_and_rule_of_law_index,demographic_pressures,refugees_and_displaced_persons_index,external_interventions_index,fragile_state_score
1206,Iceland,ISL,2007,21.1,1.0,0.8,1.0,3.5,2.5,3.2,1.3,1.3,2.1,1.0,0.9,2.5,83.109244
1207,Iceland,ISL,2008,20.9,1.0,0.8,1.0,3.0,2.8,3.2,1.3,1.3,2.1,1.0,0.9,2.5,83.277311
1208,Iceland,ISL,2009,29.0,1.0,2.0,1.0,6.7,2.5,3.2,2.2,1.4,2.1,1.0,0.9,5.0,76.470588
1209,Iceland,ISL,2010,29.8,1.1,2.0,1.0,7.2,2.3,3.0,2.0,1.5,1.9,0.8,1.1,5.9,75.798319
1210,Iceland,ISL,2011,30.1,1.0,1.8,1.0,6.2,2.2,3.3,2.0,1.9,1.6,1.6,1.5,6.0,75.546218
1211,Iceland,ISL,2012,29.1,1.3,1.8,1.0,5.7,1.9,3.1,1.7,1.9,1.6,1.9,1.3,5.7,76.386555
1212,Iceland,ISL,2013,24.7,1.0,1.8,1.0,3.7,1.7,2.8,1.4,1.6,1.3,1.6,1.6,5.2,80.084034
1213,Iceland,ISL,2014,25.9,1.3,1.8,1.0,3.9,1.9,3.1,1.2,1.9,1.4,1.9,1.6,4.9,79.075630
1214,Iceland,ISL,2015,23.4,1.0,1.8,1.3,3.6,1.6,2.8,0.9,1.7,1.1,1.6,1.4,4.6,81.176471
1215,Iceland,ISL,2016,22.8,1.2,1.8,1.3,3.5,1.3,2.5,1.0,1.4,1.0,1.8,1.7,4.3,81.680672
1216,Iceland,ISL,2017,22.5,1.0,1.8,1.3,3.3,1.1,2.8,1.3,1.2,1.0,1.6,2.0,4.1,81.932773
1217,Iceland,ISL,2018,20.3,0.8,1.8,1.1,3.2,0.9,2.6,1.0,1.0,0.8,1.4,1.8,3.9,83.781513
1218,Iceland,ISL,2019,19.8,0.7,1.8,1.0,3.1,0.9,2.5,1.0,1.0,1.0,1.3,1.7,3.8,84.201681
1219,Iceland,ISL,2020,17.8,1.0,1.8,0.7,2.8,1.0,2.2,0.7,0.7,0.7,1.0,1.7,3.5,85.882353
1220,Iceland,ISL,2021,18.0,0.7,1.8,0.5,3.4,1.3,1.9,0.5,1.2,0.5,1.5,1.5,3.2,85.714286
1221,Iceland,ISL,2022,17.1,0.4,1.8,0.5,3.1,1.4,1.7,0.4,0.9,0.4,1.8,1.8,2.9,86.470588
1222,Iceland,ISL,2023,15.7,0.4,1.8,0.5,2.6,1.5,1.6,0.4,0.9,NaN,1.5,1.5,NaN,87.647059

In [28]:
country_code_mapping = {
    'NZ': 'NZL', 'NO': 'NOR', 'SE': 'SWE', 'FI': 'FIN', 'CA': 'CAN', 'PY': 'PRY', 'AU': 'AUS', 'CF': 'CAF',
    'SI': 'SVN', 'AT': 'AUT', 'BR': 'BRA', 'CH': 'CHE', 'CR': 'CRI', 'CO': 'COL', 'LV': 'LVA', 'ZM': 'ZMB',
    'GA': 'GAB', 'RO': 'ROU', 'LT': 'LTU', 'GB': 'GBR', 'EC': 'ECU', 'HR': 'HRV', 'CL': 'CHL', 'FR': 'FRA',
    'EE': 'EST', 'BO': 'BOL', 'PA': 'PAN', 'IE': 'IRL', 'DK': 'DNK', 'MW': 'MWI', 'ES': 'ESP', 'PE': 'PER',
    'DE': 'DEU', 'SK': 'SVK', 'CD': 'COD', 'AL': 'ALB', 'JP': 'JPN', 'VE': 'VEN', 'UY': 'URY', 'PT': 'PRT',
    'UG': 'UGA', 'LA': 'LAO', 'US': 'USA', 'NP': 'NPL', 'CG': 'COG', 'GR': 'GRC', 'NL': 'NLD', 'RU': 'RUS',
    'IT': 'ITA', 'MZ': 'MOZ', 'CZ': 'CZE', 'HU': 'HUN', 'NI': 'NIC', 'GQ': 'GNQ', 'PL': 'POL', 'TJ': 'TJK',
    'BG': 'BGR', 'BE': 'BEL', 'MN': 'MNG', 'HN': 'HND', 'GE': 'GEO', 'ET': 'ETH', 'CM': 'CMR', 'ML': 'MLI',
    'KG': 'KGZ', 'MY': 'MYS', 'NE': 'NER', 'PG': 'PNG', 'MX': 'MEX', 'AR': 'ARG', 'KZ': 'KAZ', 'GN': 'GIN',
    'BW': 'BWA', 'BI': 'BDI', 'KH': 'KHM', 'BY': 'BLR', 'ZW': 'ZWE', 'MK': 'MKD', 'RS': 'SRB', 'TL': 'TLS',
    'SL': 'SLE', 'AE': 'ARE', 'MM': 'MMR', 'BF': 'BFA', 'KR': 'KOR', 'DO': 'DOM', 'RW': 'RWA', 'TH': 'THA',
    'TD': 'TCD', 'AO': 'AGO', 'KE': 'KEN', 'GH': 'GHA', 'ID': 'IDN', 'TZ': 'TZA', 'AM': 'ARM', 'UA': 'UKR',
    'GW': 'GNB', 'SN': 'SEN', 'JM': 'JAM', 'BJ': 'BEN', 'BA': 'BIH', 'MA': 'MAR', 'CU': 'CUB', 'TT': 'TTO',
    'LK': 'LKA', 'LS': 'LSO', 'PH': 'PHL', 'TG': 'TGO', 'SV': 'SLV', 'KW': 'KWT', 'GT': 'GTM', 'NG': 'NGA',
    'VN': 'VNM', 'CI': 'CIV', 'ZA': 'ZAF', 'SD': 'SDN', 'TR': 'TUR', 'AZ': 'AZE', 'LR': 'LBR', 'MG': 'MDG',
    'SS': 'SSD', 'CY': 'CYP', 'SG': 'SGP', 'JO': 'JOR', 'IL': 'ISR', 'MD': 'MDA', 'EG': 'EGY', 'IQ': 'IRQ',
    'BH': 'BHR', 'BD': 'BGD', 'GM': 'GMB', 'SA': 'SAU', 'SO': 'SOM', 'MR': 'MRT', 'CN': 'CHN', 'OM': 'OMN',
    'PK': 'PAK', 'SZ': 'SWZ', 'IN': 'IND', 'PS': 'PSE', 'IR': 'IRN', 'QA': 'QAT', 'TN': 'TUN', 'TM': 'TKM',
    'AF': 'AFG', 'DZ': 'DZA', 'HT': 'HTI', 'UZ': 'UZB', 'MU': 'MUS', 'LB': 'LBN', 'YE': 'YEM', 'LY': 'LBY',
    'SY': 'SYR'
}

sri['code'] = sri['code'].replace(country_code_mapping)

In [29]:
sri = sri[['code','sri_score']]

In [30]:
sri_fragile_score = pd.merge(sri, fragile_index_22, on=['code'], how='outer')

In [31]:
sri_fragile_score

    code  sri_score      country  fragile_state_score
0    AFG     34.375  Afghanistan            14.369748
1    AFG     34.375  Afghanistan            15.042017
2    AFG     34.375  Afghanistan            11.848739
3    AFG     34.375  Afghanistan            11.260504
4    AGO     40.250       Angola            27.478992
..   ...        ...          ...                  ...
703  ZWE     48.875     Zimbabwe            17.478992
704  ZWE     48.875     Zimbabwe            17.563025
705  ZWE     48.875     Zimbabwe            18.655462
706  ZWE     48.875     Zimbabwe            19.411765
707  NaN     58.250          NaN                  NaN

[708 rows x 4 columns]

In [32]:
sustainability_20 = sustainability[sustainability['year']>=2018]
sustainability_20

,code,year,population,sdg_index_score,1no_poverty,2no_hunger,3health_wellbeing,4quality_education,5gender_equality,6cleanwater_sanitation,...,9industry_innov_infrast,10reduced_inequalities,11cities_communities,12consumption_production,13climate,14life_below_water,15life_on_land,16peace_justice_stroninstitutions,17partnership_for_goals,tourism_score
18,AFG,2018,36160598.0,46.3,29.1,47.8,36.9,40.2,29.0,47.9,...,9.5,NaN,32.8,96.7,99.0,NaN,60.9,45.6,42.1,42.400000
19,AFG,2019,37212970.0,46.4,29.4,47.0,36.5,42.0,30.8,49.2,...,9.7,NaN,29.8,96.7,99.0,NaN,60.9,46.1,42.0,41.866667
20,AFG,2020,38326027.0,47.3,27.9,46.0,37.6,42.0,30.2,50.4,...,9.8,NaN,30.2,96.7,99.0,NaN,73.2,45.3,44.1,42.266667
39,ALB,2018,2878389.0,73.5,97.4,57.6,82.5,96.1,56.1,73.5,...,38.7,90.5,80.6,81.8,90.3,45.4,80.2,64.1,65.4,76.114286
40,ALB,2019,2875637.0,73.7,98.5,58.3,82.6,95.2,57.4,73.6,...,39.3,88.1,78.1,81.7,90.3,49.4,80.1,63.4,65.7,75.528571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3757,ZMB,2019,18106035.0,53.4,10.4,58.7,42.8,66.1,65.9,52.6,...,18.9,8.3,57.1,94.9,97.9,NaN,68.9,45.4,55.3,47.985714
3758,ZMB,2020,18654918.0,53.6,9.4,59.1,45.9,66.7,66.2,52.9,...,19.8,8.3,56.9,94.9,98.0,NaN,68.9,44.4,55.2,48.414286
3777,ZWE,2018,14900379.0,55.9,26.4,46.6,39.8,57.9,76.7,51.6,...,23.5,32.4,79.2,94.6,94.1,NaN,76.4,45.5,45.6,53.342857
3778,ZWE,2019,15203989.0,53.7,21.4,46.0,40.6,60.6,77.0,51.3,...,23.8,24.0,58.6,94.6,94.2,NaN,76.4,44.0,44.5,49.128571
3779,ZWE,2020,15505226.0,54.3,20.1,47.2,41.5,62.0,77.0,51.1,...,25.4,24.0,60.0,94.6,94.3,NaN,76.4,44.6,46.0,49.957143

In [42]:
sustainability_plus = pd.merge(sri_fragile_score, sustainability_20, on=['code'], how='outer')

In [43]:
sustainability_plus

,code,sri_score,country,fragile_state_score,year,population,sdg_index_score,1no_poverty,2no_hunger,3health_wellbeing,...,9industry_innov_infrast,10reduced_inequalities,11cities_communities,12consumption_production,13climate,14life_below_water,15life_on_land,16peace_justice_stroninstitutions,17partnership_for_goals,tourism_score
0,AFG,34.375,Afghanistan,14.369748,2018.0,36160598.0,46.3,29.1,47.8,36.9,...,9.5,NaN,32.8,96.7,99.0,NaN,60.9,45.6,42.1,42.400000
1,AFG,34.375,Afghanistan,14.369748,2019.0,37212970.0,46.4,29.4,47.0,36.5,...,9.7,NaN,29.8,96.7,99.0,NaN,60.9,46.1,42.0,41.866667
2,AFG,34.375,Afghanistan,14.369748,2020.0,38326027.0,47.3,27.9,46.0,37.6,...,9.8,NaN,30.2,96.7,99.0,NaN,73.2,45.3,44.1,42.266667
3,AFG,34.375,Afghanistan,15.042017,2018.0,36160598.0,46.3,29.1,47.8,36.9,...,9.5,NaN,32.8,96.7,99.0,NaN,60.9,45.6,42.1,42.400000
4,AFG,34.375,Afghanistan,15.042017,2019.0,37212970.0,46.4,29.4,47.0,36.5,...,9.7,NaN,29.8,96.7,99.0,NaN,60.9,46.1,42.0,41.866667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2055,_UMIC,NaN,NaN,NaN,2020.0,NaN,71.3,92.5,74.3,80.5,...,72.3,31.9,79.0,84.8,84.5,57.7,53.9,60.5,58.1,70.357143
2056,_World,NaN,NaN,NaN,2018.0,NaN,65.5,77.7,65.0,69.4,...,58.1,38.5,66.2,85.0,86.3,59.1,57.4,58.1,55.5,64.714286
2057,_World,NaN,NaN,NaN,2019.0,NaN,66.0,78.5,65.2,70.0,...,60.4,38.5,66.8,84.9,86.3,61.8,57.4,58.3,55.8,65.314286
2058,_World,NaN,NaN,NaN,2020.0,NaN,66.2,77.1,64.9,70.5,...,62.8,38.9,66.9,85.0,86.7,62.0,57.4,57.9,56.4,65.800000
2059,NaN,58.250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
sustainability_plus['global_score'] = sustainability_plus[['sri_score', 'fragile_state_score', 'sdg_index_score']].mean(axis=1)

In [45]:
sustainability_plus = sustainability_plus.sort_values(by='global_score', ascending=False)
sustainability_plus

,code,sri_score,country,fragile_state_score,year,population,sdg_index_score,1no_poverty,2no_hunger,3health_wellbeing,...,10reduced_inequalities,11cities_communities,12consumption_production,13climate,14life_below_water,15life_on_land,16peace_justice_stroninstitutions,17partnership_for_goals,tourism_score,global_score
625,FIN,82.75,Finland,88.571429,2020.0,5525215.0,86.4,99.5,62.4,95.5,...,98.5,91.2,57.7,68.8,88.1,85.1,92.5,71.4,89.914286,85.907143
624,FIN,82.75,Finland,88.571429,2019.0,5517858.0,86.1,99.6,63.6,95.6,...,97.2,89.2,57.7,67.3,88.0,85.1,91.7,69.6,89.200000,85.807143
631,FIN,82.75,Finland,88.151261,2020.0,5525215.0,86.4,99.5,62.4,95.5,...,98.5,91.2,57.7,68.8,88.1,85.1,92.5,71.4,89.914286,85.767087
630,FIN,82.75,Finland,88.151261,2019.0,5517858.0,86.1,99.6,63.6,95.6,...,97.2,89.2,57.7,67.3,88.0,85.1,91.7,69.6,89.200000,85.667087
623,FIN,82.75,Finland,88.571429,2018.0,5513064.0,85.6,99.5,61.4,95.2,...,98.4,91.2,57.8,66.3,85.3,85.1,90.6,69.0,89.242857,85.640476
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1504,PRK,NaN,North Korea,25.042017,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.042017
586,ERI,NaN,Eritrea,21.428571,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.428571
583,ERI,NaN,Eritrea,20.336134,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.336134
585,ERI,NaN,Eritrea,20.252101,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.252101
584,ERI,NaN,Eritrea,19.327731,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.327731

In [63]:
sustainability_plus = sustainability_plus.groupby(['code','country']).mean()

In [79]:
sustainability_plus['global_rank'] = sustainability_plus['global_score'].rank(ascending=False).astype(int)

In [64]:
sustainability_plus['country'].unique()

KeyError: 'country'

In [65]:
sustainability_plus['global_rank'] = sustainability_plus['global_score'].rank(ascending=False).astype(int)

In [80]:
sustainability_top_countries = sustainability_plus.reset_index()
sustainability_top_countries

,code,country,sri_score,fragile_state_score,year,population,sdg_index_score,1no_poverty,2no_hunger,3health_wellbeing,...,11cities_communities,12consumption_production,13climate,14life_below_water,15life_on_land,16peace_justice_stroninstitutions,17partnership_for_goals,tourism_score,global_score,global_rank
0,AFG,Afghanistan,34.375,13.130252,2019.0,3.723320e+07,46.666667,28.800000,46.933333,37.000000,...,30.933333,96.700000,99.000000,NaN,65.000000,45.666667,42.733333,42.177778,31.390640,170
1,AGO,Angola,40.250,27.037815,2019.0,3.181535e+07,50.800000,34.533333,56.133333,34.933333,...,43.200000,94.100000,96.166667,67.533333,66.200000,43.200000,50.666667,43.600000,39.362605,155
2,ALB,Albania,58.500,52.247899,2019.0,2.875385e+06,73.633333,98.100000,58.300000,82.600000,...,78.433333,81.733333,90.366667,48.366667,80.066667,63.666667,65.666667,75.719048,61.460411,52
3,ARE,United Arab Emirates,63.875,68.382353,2019.0,9.175963e+06,68.833333,99.666667,64.700000,85.533333,...,83.666667,49.366667,9.800000,72.533333,56.400000,73.700000,34.800000,70.766667,67.030229,37
4,ARG,Argentina,61.750,60.819328,2019.0,4.457854e+07,72.900000,96.266667,68.833333,80.766667,...,83.233333,78.166667,89.100000,61.366667,59.133333,63.100000,63.500000,70.700000,65.156443,44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,WSM,Samoa,NaN,46.764706,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.764706,129
174,YEM,Yemen,29.000,7.415966,2019.0,3.116938e+07,46.733333,9.033333,27.866667,44.633333,...,48.266667,95.966667,98.700000,75.100000,49.100000,35.666667,51.800000,51.571429,27.716433,176
175,ZAF,South Africa,56.875,41.155462,2019.0,5.771514e+07,63.166667,51.166667,56.133333,53.633333,...,79.766667,84.200000,82.133333,69.733333,58.033333,56.666667,71.466667,58.671429,53.732376,102
176,ZMB,Zambia,49.375,30.504202,2019.0,1.810890e+07,53.466667,10.166667,58.566667,43.500000,...,57.733333,94.933333,97.933333,NaN,68.900000,44.900000,55.366667,48.200000,44.448623,137
177,ZWE,Zimbabwe,48.875,18.277311,2019.0,1.520320e+07,54.633333,22.633333,46.600000,40.633333,...,65.933333,94.600000,94.200000,NaN,76.400000,44.700000,45.366667,50.809524,40.595215,151

In [81]:
sustainability_top_countries = sustainability_top_countries[sustainability_top_countries['country'].isin(top28_countries)]

In [82]:
sustainability_top_countries

,code,country,sri_score,fragile_state_score,year,population,sdg_index_score,1no_poverty,2no_hunger,3health_wellbeing,...,11cities_communities,12consumption_production,13climate,14life_below_water,15life_on_land,16peace_justice_stroninstitutions,17partnership_for_goals,tourism_score,global_score,global_rank
3,ARE,United Arab Emirates,63.875,68.382353,2019.0,9.175963e+06,68.833333,99.666667,64.700000,85.533333,...,83.666667,49.366667,9.800000,72.533333,56.400000,73.700000,34.800000,70.766667,67.030229,37
8,AUT,Austria,78.250,79.831933,2019.0,8.860710e+06,82.933333,99.433333,72.533333,92.800000,...,91.366667,49.566667,57.066667,NaN,73.600000,91.233333,67.033333,85.738095,80.338422,11
28,CAN,Canada,78.500,84.159664,2019.0,3.727625e+07,77.966667,99.600000,65.266667,94.133333,...,91.166667,51.700000,38.133333,61.800000,60.600000,83.900000,73.033333,80.304762,80.208777,12
31,CHN,China,59.750,43.949580,2019.0,1.419379e+09,71.300000,96.166667,83.066667,81.866667,...,78.366667,87.066667,78.933333,54.800000,49.600000,59.766667,41.700000,70.623810,58.333193,71
42,CZE,Czechia,69.750,68.256303,2019.0,1.053570e+07,81.266667,99.866667,61.166667,90.433333,...,93.366667,58.233333,71.833333,NaN,92.700000,82.066667,57.933333,85.666667,73.090990,26
43,DEU,Germany,78.750,80.630252,2019.0,8.302035e+07,82.633333,99.500000,71.866667,93.733333,...,92.200000,53.066667,63.433333,72.600000,79.166667,89.466667,77.400000,85.152381,80.671195,9
45,DNK,Denmark,82.000,85.714286,2019.0,5.781383e+06,84.800000,99.233333,70.833333,95.333333,...,92.200000,37.266667,60.200000,74.766667,92.800000,93.866667,81.133333,88.104762,84.171429,4
51,ESP,Spain,72.625,64.474790,2019.0,4.697135e+07,79.466667,98.700000,65.100000,94.766667,...,91.466667,64.300000,79.733333,57.966667,66.500000,80.233333,57.466667,84.509524,72.188819,27
56,FRA,France,74.875,75.063025,2019.0,6.433779e+07,81.333333,99.700000,71.933333,93.233333,...,90.766667,58.833333,73.800000,64.233333,68.400000,76.166667,68.266667,85.590476,77.090453,15
59,GBR,United Kingdom,77.125,66.743697,2019.0,6.660572e+07,81.066667,98.966667,67.900000,93.633333,...,93.433333,54.200000,70.600000,75.266667,86.200000,82.866667,61.666667,82.238095,74.978455,20
66,GRC,Greece,66.625,55.147059,2019.0,1.060330e+07,77.433333,99.400000,66.166667,89.966667,...,83.266667,66.900000,79.033333,63.900000,81.366667,74.066667,58.500000,79.819048,66.401797,40
71,HRV,Croatia,65.250,60.105042,2019.0,4.145203e+06,80.800000,100.000000,74.266667,86.966667,...,81.100000,72.666667,83.733333,84.333333,88.200000,72.400000,50.966667,83.190476,68.718347,35
73,HUN,Hungary,65.000,59.180672,2019.0,9.774278e+06,79.200000,98.800000,71.266667,83.433333,...,88.200000,74.100000,77.900000,NaN,86.433333,68.833333,50.766667,82.080952,67.793557,36
81,ITA,Italy,70.000,64.369748,2019.0,5.979825e+07,78.133333,97.433333,69.566667,94.066667,...,73.700000,70.766667,79.900000,61.500000,79.900000,72.833333,60.666667,80.976190,70.834360,32
84,JPN,Japan,74.875,74.369748,2019.0,1.260182e+08,78.766667,99.300000,74.666667,94.066667,...,84.700000,60.900000,73.200000,54.833333,63.500000,87.200000,71.500000,83.942857,76.003805,19
105,MEX,Mexico,57.875,42.605042,2019.0,1.245461e+08,69.100000,86.900000,61.100000,78.300000,...,82.100000,79.666667,86.233333,63.233333,55.600000,47.833333,59.500000,67.880952,56.526681,87
116,MYS,Malaysia,63.250,53.382353,2019.0,3.260073e+07,69.033333,98.833333,48.966667,79.566667,...,84.566667,72.166667,77.100000,66.600000,35.366667,60.400000,56.500000,73.228571,61.888562,50
121,NLD,Netherlands,79.125,81.911765,2019.0,1.732479e+07,78.933333,99.233333,67.700000,95.766667,...,94.866667,47.733333,41.866667,54.233333,78.233333,87.333333,65.933333,81.980952,79.990033,13
131,POL,Poland,66.750,64.810924,2019.0,3.850696e+07,80.566667,98.900000,66.266667,85.100000,...,85.566667,73.900000,75.733333,71.166667,92.633333,78.066667,60.666667,82.004762,70.709197,33
138,RUS,Russia,59.250,37.920168,2019.0,1.456887e+08,73.366667,98.766667,59.166667,78.700000,...,84.333333,80.733333,70.833333,53.933333,66.066667,50.500000,70.600000,75.519048,56.845612,84
140,SAU,Saudi Arabia,50.000,43.844538,2019.0,3.542208e+07,64.600000,100.000000,57.166667,76.500000,...,61.300000,64.433333,34.600000,64.666667,49.566667,70.366667,60.800000,64.288889,52.814846,107
143,SGP,Singapore,74.125,78.949580,2019.0,5.840864e+06,70.066667,NaN,76.133333,94.600000,...,96.100000,44.166667,56.566667,46.133333,27.133333,84.466667,42.900000,80.888889,74.380415,22
151,SVK,Slovakia,68.000,68.886555,2019.0,5.450348e+06,79.133333,99.100000,71.700000,87.966667,...,86.233333,66.266667,71.066667,NaN,89.200000,78.000000,55.933333,81.671429,72.006629,28
159,THA,Thailand,60.250,42.079832,2019.0,7.121499e+07,73.600000,98.433333,59.233333,79.233333,...,85.333333,79.533333,81.400000,63.700000,58.366667,63.800000,60.200000,75.171429,58.643277,70
164,TUR,Turkey,54.625,34.012605,2019.0,8.314343e+07,70.333333,97.500000,65.566667,84.000000,...,73.233333,82.166667,87.200000,56.200000,53.900000,61.666667,74.566667,71.085714,52.990313,105
167,UKR,Ukraine,58.750,37.121849,2019.0,4.432820e+07,74.233333,NaN,65.766667,75.333333,...,79.833333,84.533333,84.900000,61.066667,79.600000,62.033333,74.166667,75.157143,56.701727,86
169,USA,USA,73.875,64.117647,2019.0,3.332228e+08,74.966667,98.766667,68.700000,88.966667,...,90.533333,54.333333,51.733333,65.033333,60.433333,69.433333,68.433333,76.619048,70.986438,31
175,ZAF,South Africa,56.875,41.155462,2019.0,5.771514e+07,63.166667,51.166667,56.133333,53.633333,...,79.766667,84.200000,82.133333,69.733333,58.033333,56.666667,71.466667,58.671429,53.732376,102

In [52]:
#sustainability_top_countries = sustainability_top_countries.groupby(['code','country']).mean()

In [76]:
sustainability_top_countries['country'].nunique()

28

In [77]:
sustainability_top_countries['country'].unique()

array(['United Arab Emirates', 'Austria', 'Canada', 'China', 'Czechia',
       'Germany', 'Denmark', 'Spain', 'France', 'United Kingdom',
       'Greece', 'Croatia', 'Hungary', 'Italy', 'Japan', 'Mexico',
       'Malaysia', 'Netherlands', 'Poland', 'Russia', 'Saudi Arabia',
       'Singapore', 'Slovakia', 'Thailand', 'Turkey', 'Ukraine', 'USA',
       'South Africa'], dtype=object)

In [110]:
arrivals = pd.read_csv('./data/tourism_arrival_departure.csv')

In [111]:
arrivals = arrivals.groupby(['code','country','entity']).mean()

In [112]:
arrivals = arrivals.reset_index()

In [113]:
arrivals = arrivals.drop(columns=['Unnamed: 0','entity','tourist_departures','year'])

In [119]:
arrivals['country'].unique()

array(['Aruba', 'Afghanistan', 'Angola', 'Albania',
       'United Arab Emirates', 'Argentina', 'Armenia',
       'Antigua and Barbuda', 'Australia', 'Austria', 'Azerbaijan',
       'Burundi', 'Belgium', 'Benin', 'Burkina Faso', 'Bangladesh',
       'Bulgaria', 'Bahrain', 'Bahamas, The', 'Bosnia and Herzegovina',
       'Belarus', 'Belize', 'Bermuda', 'Bolivia', 'Brazil', 'Barbados',
       'Brunei Darussalam', 'Bhutan', 'Botswana',
       'Central African Republic', 'Canada', 'Switzerland', 'Chile',
       'China', "China (People's Republic of)", "Cote d'Ivoire",
       'Cameroon', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Colombia',
       'Comoros', 'Cabo Verde', 'Cyprus', 'Czechia', 'Germany',
       'Djibouti', 'Dominica', 'Denmark', 'Dominican Republic', 'Algeria',
       'Ecuador', 'Egypt', 'Egypt, Arab Rep.', 'Eritrea', 'Spain',
       'Estonia', 'Ethiopia', 'Finland', 'Fiji', 'France',
       'Faroe Islands', 'Micronesia, Fed. Sts.', 'Gabon',
       'United Kingdom', 'Georgia', 'Ghana', 'Guinea', 'Gambia, The',
       'Guinea-Bissau', 'Equatorial Guinea', 'Greece', 'Grenada',
       'Guatemala', 'Guyana', 'Hong Kong SAR, China', 'Honduras',
       'Croatia', 'Haiti', 'Hungary', 'Indonesia', 'India', 'Ireland',
       'Iran, Islamic Rep.', 'Iraq', 'Iceland', 'Israel', 'Italy',
       'Jamaica', 'Jordan', 'Japan', 'Kazakhstan', 'Kenya',
       'Kyrgyz Republic', 'Cambodia', 'Kiribati', 'Korea', 'Korea, Rep.',
       'Kuwait', 'Lao PDR', 'Lebanon', 'Liberia', 'Libya', 'St. Lucia',
       'Sri Lanka', 'Lesotho', 'Lithuania', 'Luxembourg', 'Latvia',
       'Macao SAR, China', 'Morocco', 'Moldova', 'Madagascar', 'Maldives',
       'Mexico', 'North Macedonia', 'Mali', 'Malta', 'Myanmar',
       'Montenegro', 'Mongolia', 'Mozambique', 'Mauritania', 'Mauritius',
       'Malawi', 'Malaysia', 'Namibia', 'New Caledonia', 'Niger',
       'Nigeria', 'Nicaragua', 'Netherlands', 'Norway', 'Nepal',
       'New Zealand', 'Oman', 'Pakistan', 'Panama', 'Peru', 'Philippines',
       'Papua New Guinea', 'Poland', 'Portugal', 'Paraguay', 'Qatar',
       'Romania', 'Russia', 'Russian Federation', 'Rwanda',
       'Saudi Arabia', 'Sudan', 'Senegal', 'Singapore', 'Solomon Islands',
       'Sierra Leone', 'El Salvador', 'Somalia', 'Serbia',
       'Sao Tome and Principe', 'Suriname', 'Slovak Republic', 'Slovenia',
       'Sweden', 'Eswatini', 'Seychelles', 'Syrian Arab Republic', 'Chad',
       'Togo', 'Thailand', 'Tajikistan', 'Turkmenistan', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkiye', 'Türkiye', 'Tuvalu',
       'Tanzania', 'Uganda', 'Ukraine', 'Uruguay', 'United States',
       'Uzbekistan', 'St. Vincent and the Grenadines', 'Venezuela, RB',
       'Viet Nam', 'Vanuatu', 'Samoa', 'Yemen, Rep.', 'South Africa',
       'Zambia', 'Zimbabwe'], dtype=object)

In [120]:
top30_countries = ['United States', 'Spain', 'France', 'United Kingdom', 
                   'Germany', 'Italy', 'Thailand', 'Turkiye', 'Hong Kong SAR China', 
                   'Macao SAR, China', "China (People's Republic of)", 'Canada', 'Japan', 'Austria', 
                   'Netherlands', 'Malaysia', 'Mexico', 'Greece', 'United Arab Emirates', 
                   'Singapore' ,'Russian Federation', 'Poland', 'Saudi Arabia', 
                   'Croatia', 'South Africa', 'Denmark' ,'Czechia', 'Hungary', 
                   'Ukraine', 'Slovak Republic']

In [122]:
arrival = arrivals[arrivals['country'].isin(top30_countries)]

In [123]:
arrival = arrival.drop(columns=['country'])

In [124]:
sustainability_top_countries_arrivals = pd.merge(sustainability_top_countries, arrival, on=['code'], how='left')
sustainability_top_countries_arrivals['country'].nunique()

28

In [125]:
sustainability_top_countries_arrivals

,code,country,sri_score,fragile_state_score,year,population,sdg_index_score,1no_poverty,2no_hunger,3health_wellbeing,...,17partnership_for_goals,tourism_score,global_score,global_rank,arrivals,revenue_dollars,gdp_dollars,percent_of_gdp,primary_energy_consumption_per_capita_kwh/person,annual_co2_emissions_per_capita)
0,ARE,United Arab Emirates,63.875,68.382353,2019.0,9.175963e+06,68.833333,99.666667,64.700000,85.533333,...,34.800000,70.766667,67.030229,37,1.974500e+07,1.498390e+10,3.159100e+11,4.189624,136910.315278,24.113671
1,AUT,Austria,78.250,79.831933,2019.0,8.860710e+06,82.933333,99.433333,72.533333,92.800000,...,67.033333,85.738095,80.338422,11,2.382524e+07,1.998224e+10,3.975921e+11,5.036527,48373.322158,8.265923
2,CAN,Canada,78.500,84.159664,2019.0,3.727625e+07,77.966667,99.600000,65.266667,94.133333,...,73.033333,80.304762,80.208777,12,2.937788e+07,2.099849e+10,1.556232e+12,1.356677,112214.084263,16.351894
3,CHN,China,59.750,43.949580,2019.0,1.419379e+09,71.300000,96.166667,83.066667,81.866667,...,41.700000,70.623810,58.333193,71,NaN,4.355431e+10,9.557775e+12,0.520852,24148.215500,6.879241
4,CZE,Czechia,69.750,68.256303,2019.0,1.053570e+07,81.266667,99.866667,61.166667,90.433333,...,57.933333,85.666667,73.090990,26,2.723188e+07,7.118441e+09,1.981511e+11,3.668023,47606.346778,10.908510
5,DEU,Germany,78.750,80.630252,2019.0,8.302035e+07,82.633333,99.500000,71.866667,93.733333,...,77.400000,85.152381,80.671195,9,2.869441e+07,4.644549e+10,3.461573e+12,1.345946,46805.655222,9.915572
6,DNK,Denmark,82.000,85.714286,2019.0,5.781383e+06,84.800000,99.233333,70.833333,95.333333,...,81.133333,88.104762,84.171429,4,2.689124e+07,8.059334e+09,3.216979e+11,2.503752,38060.387737,7.782570
7,ESP,Spain,72.625,64.474790,2019.0,4.697135e+07,79.466667,98.700000,65.100000,94.766667,...,57.466667,84.509524,72.188819,27,9.992671e+07,6.655021e+10,1.321116e+12,4.833591,36468.530389,6.464624
8,FRA,France,74.875,75.063025,2019.0,6.433779e+07,81.333333,99.700000,71.933333,93.233333,...,68.266667,85.590476,77.090453,15,1.944004e+08,6.069354e+10,2.572769e+12,2.365996,46578.259444,5.785815
9,GBR,United Kingdom,77.125,66.743697,2019.0,6.660572e+07,81.066667,98.966667,67.900000,93.633333,...,61.666667,82.238095,74.978455,20,3.287218e+07,5.207804e+10,2.699111e+12,1.883839,38127.465056,7.539518
10,GRC,Greece,66.625,55.147059,2019.0,1.060330e+07,77.433333,99.400000,66.166667,89.966667,...,58.500000,79.819048,66.401797,40,2.279118e+07,1.559901e+10,2.461326e+11,6.581500,32479.072579,8.139278
11,HRV,Croatia,65.250,60.105042,2019.0,4.145203e+06,80.800000,100.000000,74.266667,86.966667,...,50.966667,83.190476,68.718347,35,4.984129e+07,8.931797e+09,5.624368e+10,15.982883,23286.432579,4.697175
12,HUN,Hungary,65.000,59.180672,2019.0,9.774278e+06,79.200000,98.800000,71.266667,83.433333,...,50.766667,82.080952,67.793557,36,4.407365e+07,6.532177e+09,1.362300e+11,4.801365,27573.116211,5.218141
13,ITA,Italy,70.000,64.369748,2019.0,5.979825e+07,78.133333,97.433333,69.566667,94.066667,...,60.666667,80.976190,70.834360,32,7.409151e+07,4.241580e+10,2.028433e+12,2.091587,33111.542167,6.975174
14,JPN,Japan,74.875,74.369748,2019.0,1.260182e+08,78.766667,99.300000,74.666667,94.066667,...,71.500000,83.942857,76.003805,19,1.354752e+07,2.094362e+10,5.099419e+12,0.416076,44325.161722,9.632698
15,MEX,Mexico,57.875,42.605042,2019.0,1.245461e+08,69.100000,86.900000,61.100000,78.300000,...,59.500000,67.880952,56.526681,87,8.791818e+07,1.563088e+10,1.122788e+12,1.388740,18583.608111,4.103036
16,MYS,Malaysia,63.250,53.382353,2019.0,3.260073e+07,69.033333,98.833333,48.966667,79.566667,...,56.500000,73.228571,61.888562,50,2.226588e+07,1.718617e+10,2.599839e+11,6.820322,34202.777333,7.240672
17,NLD,Netherlands,79.125,81.911765,2019.0,1.732479e+07,78.933333,99.233333,67.700000,95.766667,...,65.933333,81.980952,79.990033,13,1.276082e+07,1.964453e+10,8.335695e+11,2.342255,63581.916526,9.887852
18,POL,Poland,66.750,64.810924,2019.0,3.850696e+07,80.566667,98.900000,66.266667,85.100000,...,60.666667,82.004762,70.709197,33,7.004006e+07,1.090780e+10,4.629033e+11,2.360404,29302.003333,8.411759
19,RUS,Russia,59.250,37.920168,2019.0,1.456887e+08,73.366667,98.766667,59.166667,78.700000,...,70.600000,75.519048,56.845612,84,2.419394e+07,1.338244e+10,1.452631e+12,0.958433,54990.027111,11.314216
20,SAU,Saudi Arabia,50.000,43.844538,2019.0,3.542208e+07,64.600000,100.000000,57.166667,76.500000,...,60.800000,64.288889,52.814846,107,1.673494e+07,9.964933e+09,5.823228e+11,1.559263,82505.545056,17.771575
21,SGP,Singapore,74.125,78.949580,2019.0,5.840864e+06,70.066667,NaN,76.133333,94.600000,...,42.900000,80.888889,74.380415,22,1.273556e+07,1.356138e+10,2.537183e+11,5.457517,145047.570833,8.840450
22,SVK,Slovakia,68.000,68.886555,2019.0,5.450348e+06,79.133333,99.100000,71.700000,87.966667,...,55.933333,81.671429,72.006629,28,1.452600e+07,2.236474e+09,9.013263e+10,2.459419,36747.036474,6.945356
23,THA,Thailand,60.250,42.079832,2019.0,7.121499e+07,73.600000,98.433333,59.233333,79.233333,...,60.200000,75.171429,58.643277,70,2.283375e+07,3.200917e+10,3.517589e+11,8.706141,17874.019333,3.613229
24,TUR,Turkey,54.625,34.012605,2019.0,8.314343e+07,70.333333,97.500000,65.566667,84.000000,...,74.566667,71.085714,52.990313,105,3.302153e+07,2.916606e+10,7.296817e+11,3.749362,18179.655389,4.501708
25,UKR,Ukraine,58.750,37.121849,2019.0,4.432820e+07,74.233333,NaN,65.766667,75.333333,...,74.166667,75.157143,56.701727,86,1.914953e+07,3.518111e+09,1.296522e+11,2.716776,28847.772667,6.088169
26,USA,USA,73.875,64.117647,2019.0,3.332228e+08,74.966667,98.766667,68.700000,88.966667,...,68.433333,76.619048,70.986438,31,1.516961e+08,1.669443e+11,1.674817e+13,1.002926,82697.688526,17.689409
27,ZAF,South Africa,56.875,41.155462,2019.0,5.771514e+07,63.166667,51.166667,56.133333,53.633333,...,71.466667,58.671429,53.732376,102,1.143315e+07,8.667282e+09,3.537537e+11,2.509022,26451.693684,8.487700

In [126]:
sustainability_top_countries_arrivals.to_csv('./data_visu/04_sustainability/sustainability_top_countries_arrivals.csv')

In [83]:
sustainability_top_countries.to_csv('./data_visu/04_sustainability/sustainability_top_countries.csv')

In [ ]:
sustainability_plus.to_csv('./data_visu/04_sustainability/sustainability_plus.csv')

In [ ]:
top30_sustain_countries = sustainability_plus.head(30)
top30_sustain_countries[top30_sustain_countries['country']=='Iceland']

In [ ]:
top30_sustain_countries = top30_sustain_countries.reset_index(drop=True)

In [ ]:
sustainability_plus= pd.merge(sustainability_plus, sustainability_tourism_rank, on='code', how='left')
sustainability_plus

In [ ]:
sustainability_plus['global_score_2'] = sustainability_plus[['sri_score', 'fragile_state_score', 'tourism_score_y']].mean(axis=1)

In [ ]:
sustainability_plus['global_rank_2']= sustainability_plus['global_score_2'].rank(ascending=False).astype(int)

In [ ]:
sustainability_plus.sort_values(by=['global_rank'], ascending=False)

In [ ]:
top30_sustain_countries_2 = sustainability_plus.head(30)

In [ ]:
top30_sustain_countries_2.sort_values(by=['global_rank'], ascending=True)

In [ ]:
top30_sustain_countries_2.to_csv('./data_visu/04_sustainability/top30_sustain_countries_2.csv')

In [ ]:
top30_sustain_countries_2['country_x'].unique()

In [ ]:
top30_countries_sust = ['Finland', 'Norway', 'Sweden', 'Denmark', 'Switzerland', nan,
       'New Zealand', 'Germany', 'Ireland', 'Canada', 'Austria',
       'Netherlands', 'Australia', 'France', 'Slovenia', 'Portugal',
       'Japan', 'Belgium', 'United Kingdom', 'Estonia', 'South Korea',
       'Singapore', 'Uruguay', 'Czechia', 'Slovakia', 'Spain',
       'Costa Rica', 'Lithuania']